[package]
name = "hyperlane-cli"
version = "0.1.18"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A command-line tool for Hyperlane framework."""
keywords = ["output", "console", "log", "print", "color"]
repository = "https://github.com/hyperlane-dev/hyperlane-cli"
categories = ["command-line-interface", "development-tools", "visualization"]
exclude = ["target", "Cargo.lock", "sh", ".github", "tmp"]

[[bin]]
name = "hyperlane"
path = "src/main.rs"

[dependencies]
toml = "0.9.12"
regex = "1.12.3"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
log = "0.4.32"
which = "8.0.2"
notify = { version = "8.2.0", default-features = false, features = [
    "macos_fsevent",
] }
color-output = "10.0.3"
lombok-macros = "2.0.28"

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
